
spring:
  application:
    name: to-do

  datasource:
    driver-class-name: org.postgresql.Driver
    password: 234569
    url: jdbc:postgresql://localhost:5432/todo
    username: postgres

  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

#  security:
#    user:
#      name: hussam
#      password: 1234567

  
management:
  endpoints:
    web:
      exposure:
        include: health, metrics

      base-path: /actuator

  endpoint:
    health:
      show-details: always
